#:kivy 2.1.0

#:import NoTransition kivy.uix.screenmanager.NoTransition
#:include screen_home.kv
#:include screen_login.kv
#:include screen_main.kv
#:include screen_Head_lamp.kv
#:include screen_Calibration.kv

# ScreenManager:
<RootScreen>:
    id: screen_manager
    transition: NoTransition()

    ScreenHome:
        id: screen_home
        name: 'screen_home'
        screen_manager: screen_manager

    ScreenLogin:
        id: screen_login
        name: 'screen_login'
        screen_manager: screen_manager

    ScreenMain:
        id: screen_main
        name: 'screen_main'
        screen_manager: screen_manager

    ScreenHeadlamp:
        id: screen_Head_lamp
        name: 'screen_Head_lamp'
        screen_manager: screen_manager   

    ScreenCalibration:
        id: screen_Calibration
        name: 'screen_Calibration'
        screen_manager: screen_manager           

